In [1]:
import pandas as pd

In [2]:
import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
titanic_train = pd.read_csv("https://gist.githubusercontent.com/michhar/2dfd2de0d4f8727f873422c5d959fff5/raw/ff414a1bcfcba32481e4d4e8db578e55872a2ca1/titanic.csv",
                           sep='\t')   
titanic_train

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0              1         0       3  ...   7.2500   NaN         S
1              2         1       1  ...  71.2833   C85         C
2              3         1       3  ...   7.9250   NaN         S
3              4         1       1  ...  53.1000  C123         S
4              5         0       3  ...   8.0500   NaN         S
..           ...       ...     ...  ...      ...   ...       ...
151          152         1       1  ...  66.6000    C2         S
152          153         0       3  ...   8.0500   NaN         S
153          154         0       3  ...  14.5000   NaN         S
154          155         0       3  ...   7.3125   NaN         S
155          156         0       1  ...  61.3792   NaN         C

[156 rows x 12 columns]

In [4]:
titanic_train.tail(10)

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
146          147         1       3  ...   7.7958   NaN         S
147          148         0       3  ...  34.3750   NaN         S
148          149         0       2  ...  26.0000    F2         S
149          150         0       2  ...  13.0000   NaN         S
150          151         0       2  ...  12.5250   NaN         S
151          152         1       1  ...  66.6000    C2         S
152          153         0       3  ...   8.0500   NaN         S
153          154         0       3  ...  14.5000   NaN         S
154          155         0       3  ...   7.3125   NaN         S
155          156         0       1  ...  61.3792   NaN         C

[10 rows x 12 columns]

In [5]:
titanic_train.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [6]:
titanic_train.dtypes == "object"
a = titanic_train.dtypes[titanic_train.dtypes == "object"].index
a
titanic_train[a].describe()


Name   Sex Ticket Cabin Embarked
count                               156   156    156    31      155
unique                              156     2    145    28        3
top     Turpin, Mr. William John Robert  male  19950   D26        S
freq                                  1   100      2     2      110

In [7]:
titanic_train.describe()

PassengerId    Survived      Pclass  ...       SibSp       Parch        Fare
count   156.000000  156.000000  156.000000  ...  156.000000  156.000000  156.000000
mean     78.500000    0.346154    2.423077  ...    0.615385    0.397436   28.109587
std      45.177428    0.477275    0.795459  ...    1.056235    0.870146   39.401047
min       1.000000    0.000000    1.000000  ...    0.000000    0.000000    6.750000
25%      39.750000    0.000000    2.000000  ...    0.000000    0.000000    8.003150
50%      78.500000    0.000000    3.000000  ...    0.000000    0.000000   14.454200
75%     117.250000    1.000000    3.000000  ...    1.000000    0.000000   30.371850
max     156.000000    1.000000    3.000000  ...    5.000000    5.000000  263.000000

[8 rows x 7 columns]

In [8]:
titanic_train.dtypes[titanic_train.dtypes == "object"].index

Index(['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked'], dtype='object')

In [9]:
titanic_train.dtypes[titanic_train.dtypes == "object"]


titanic_train.dtypes[titanic_train.dtypes == "object"].index

Index(['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked'], dtype='object')

In [10]:
titanic_train.dtypes[titanic_train.dtypes == "object"]

Name        object
Sex         object
Ticket      object
Cabin       object
Embarked    object
dtype: object

In [11]:
list_col = titanic_train.dtypes[titanic_train.dtypes == "object"].index
titanic_train[list_col].describe()

Name   Sex Ticket Cabin Embarked
count                               156   156    156    31      155
unique                              156     2    145    28        3
top     Turpin, Mr. William John Robert  male  19950   D26        S
freq                                  1   100      2     2      110

In [12]:
titanic_train[['Name','Sex','Age']]

Name     Sex   Age
0                              Braund, Mr. Owen Harris    male  22.0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0
2                               Heikkinen, Miss. Laina  female  26.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0
4                             Allen, Mr. William Henry    male  35.0
..                                                 ...     ...   ...
151                  Pears, Mrs. Thomas (Edith Wearne)  female  22.0
152                                   Meo, Mr. Alfonzo    male  55.5
153                    van Billiard, Mr. Austin Blyler    male  40.5
154                              Olsen, Mr. Ole Martin    male   NaN
155                        Williams, Mr. Charles Duane    male  51.0

[156 rows x 3 columns]

In [13]:
sorted(titanic_train["Name"])[5:10:2]# Check the first 15 sorted names

['Andersson, Mr. August Edvard ("Wennerstrom")',
 'Andrew, Mr. Edgardo Samuel',
 'Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)']

In [14]:
titanic_train["Name"].describe()

count                                 156
unique                                156
top       Turpin, Mr. William John Robert
freq                                    1
Name: Name, dtype: object

In [15]:
titanic_train[["Ticket"]][4:9]

Ticket
4  373450
5  330877
6   17463
7  349909
8  347742

In [16]:
titanic_train["Ticket"].describe()
titanic_train.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [17]:
titanic_train["sudh"]="sdffs"
titanic_train.head()

PassengerId  Survived  Pclass  ... Cabin Embarked   sudh
0            1         0       3  ...   NaN        S  sdffs
1            2         1       1  ...   C85        C  sdffs
2            3         1       3  ...   NaN        S  sdffs
3            4         1       1  ...  C123        S  sdffs
4            5         0       3  ...   NaN        S  sdffs

[5 rows x 13 columns]

In [18]:
titanic_train["Cabin"][0:15]       # Check the first 15 tickets

0      NaN
1      C85
2      NaN
3     C123
4      NaN
5      NaN
6      E46
7      NaN
8      NaN
9      NaN
10      G6
11    C103
12     NaN
13     NaN
14     NaN
Name: Cabin, dtype: object

In [19]:
titanic_train.dtypes# Check number of unique cabins

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
sudh            object
dtype: object

In [20]:
titanic_train["Survived"]

0      0
1      1
2      1
3      1
4      0
      ..
151    1
152    0
153    0
154    0
155    0
Name: Survived, Length: 156, dtype: int64

In [21]:
titanic_train.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked', 'sudh'],
      dtype='object')

In [22]:
titanic_train.describe()

PassengerId    Survived      Pclass  ...       SibSp       Parch        Fare
count   156.000000  156.000000  156.000000  ...  156.000000  156.000000  156.000000
mean     78.500000    0.346154    2.423077  ...    0.615385    0.397436   28.109587
std      45.177428    0.477275    0.795459  ...    1.056235    0.870146   39.401047
min       1.000000    0.000000    1.000000  ...    0.000000    0.000000    6.750000
25%      39.750000    0.000000    2.000000  ...    0.000000    0.000000    8.003150
50%      78.500000    0.000000    3.000000  ...    0.000000    0.000000   14.454200
75%     117.250000    1.000000    3.000000  ...    1.000000    0.000000   30.371850
max     156.000000    1.000000    3.000000  ...    5.000000    5.000000  263.000000

[8 rows x 7 columns]

In [23]:
new_Pclass = pd.Categorical(titanic_train["Pclass"])

new_Pclass

[3, 1, 3, 1, 3, ..., 1, 3, 3, 3, 1]
Length: 156
Categories (3, int64): [1, 2, 3]

In [24]:
new_Pclass = pd.Categorical(titanic_train["Pclass"])
new_Pclass

[3, 1, 3, 1, 3, ..., 1, 3, 3, 3, 1]
Length: 156
Categories (3, int64): [1, 2, 3]

In [25]:
titanic_train["Cabin"].unique()   # Check unique cabins

array([nan, 'C85', 'C123', 'E46', 'G6', 'C103', 'D56', 'A6',
       'C23 C25 C27', 'B78', 'D33', 'B30', 'C52', 'B28', 'C83', 'F33',
       'F G73', 'E31', 'A5', 'D10 D12', 'D26', 'C110', 'B58 B60', 'E101',
       'F E69', 'D47', 'B86', 'F2', 'C2'], dtype=object)

In [26]:
import numpy as np 
char_cabin = titanic_train["Cabin"].astype(str) # Convert data to str

new_Cabin = [cabin[0] for cabin in char_cabin] # Take first letter

new_Cabin = pd.Categorical(new_Cabin)
#new_Cabin
new_Cabin


[n, C, n, C, n, ..., C, n, n, n, n]
Length: 156
Categories (8, object): [A, B, C, D, E, F, G, n]

In [27]:
titanic_train["Cabin"] = new_Cabin
titanic_train.head()

PassengerId  Survived  Pclass  ... Cabin Embarked   sudh
0            1         0       3  ...     n        S  sdffs
1            2         1       1  ...     C        C  sdffs
2            3         1       3  ...     n        S  sdffs
3            4         1       1  ...     C        S  sdffs
4            5         0       3  ...     n        S  sdffs

[5 rows x 13 columns]

In [28]:
titanic_train["Age"].isnull() 

0      False
1      False
2      False
3      False
4      False
       ...  
151    False
152    False
153    False
154     True
155    False
Name: Age, Length: 156, dtype: bool

In [29]:
missing = np.where(titanic_train["Age"].isnull() == True)
missing

(array([  5,  17,  19,  26,  28,  29,  31,  32,  36,  42,  45,  46,  47,
         48,  55,  64,  65,  76,  77,  82,  87,  95, 101, 107, 109, 121,
        126, 128, 140, 154]),)

In [30]:
np.where(titanic_train["Fare"]==max(titanic_train["Fare"]))

(array([27, 88]),)

In [31]:
titanic_train.iloc[np.where(titanic_train["Fare"]==max(titanic_train["Fare"]))]

PassengerId  Survived  Pclass  ... Cabin Embarked   sudh
27           28         0       1  ...     C        S  sdffs
88           89         1       1  ...     C        S  sdffs

[2 rows x 13 columns]

In [32]:
np.where(titanic_train["Fare"]==max(titanic_train["Fare"]))

(array([27, 88]),)

In [33]:
len(missing[0])

30

In [34]:
titanic_train["Family"] = titanic_train["SibSp"] + titanic_train["Parch"]
titanic_train["Family"]
most_family = np.where(titanic_train["Family"] == max(titanic_train["Family"]))
most_family

(array([59, 71]),)

In [35]:
titanic_train["Family"] = titanic_train["SibSp"] + titanic_train["Parch"]

most_family = np.where(titanic_train["Family"] == max(titanic_train["Family"]))
most_family
titanic_train.iloc[most_family]

PassengerId  Survived  Pclass  ... Embarked   sudh  Family
59           60         0       3  ...        S  sdffs       7
71           72         0       3  ...        S  sdffs       7

[2 rows x 14 columns]

In [36]:
import numpy as np
import pandas as pd

labels = ['a','b','c']
my_data = [10,20,30]
arr = np.array(my_data)
d = {'a':10,'b':20,'c':30}

print ("Labels:", labels)
print("My data:", my_data)
print("Dictionary:", d)
pd.Series(my_data, index=labels)

Labels: ['a', 'b', 'c']
My data: [10, 20, 30]
Dictionary: {'a': 10, 'b': 20, 'c': 30}


a    10
b    20
c    30
dtype: int64

In [37]:
pd.Series(my_data, index=labels)

a    10
b    20
c    30
dtype: int64

In [38]:
print ("\nHolding numerical data\n",'-'*25, sep='')
print(pd.Series(arr)[1])



Holding numerical data
-------------------------
20


In [39]:
print ("\nHolding text labels\n",'-'*20, sep='')
print(pd.Series(labels))



Holding text labels
--------------------
0    a
1    b
2    c
dtype: object


In [40]:

d = {'a':"kjhk",'b':20,'c':30}
d.items
pd.DataFrame(d,index = ['a','b','c'])

a   b   c
a  kjhk  20  30
b  kjhk  20  30
c  kjhk  20  30

In [41]:
print ("\nHolding objects from a dictionary\n",'-'*40, sep='')
print(pd.Series([type, sum, max]))


Holding objects from a dictionary
----------------------------------------
0             <class 'type'>
1    <built-in function sum>
2    <built-in function max>
dtype: object


In [42]:
ser1 = pd.Series([1,2,3,4],index = [2,4,6,8])
ser2 = pd.Series([1,2,5,4],['CA', 'OR', 'NV', 'AZ'])
ser1

2    1
4    2
6    3
8    4
dtype: int64

In [43]:
ser1[0:3:2]


2    1
6    3
dtype: int64

In [44]:
from numpy.random import randn as rn
#np.random.seed(101)
matrix_data = rn(5,4)
row_labels = ['A','B','C','D','E']
column_headings = ['W','X','Y','Z']

df = pd.DataFrame(matrix_data,row_labels,column_headings)
#print("\nThe data frame looks like\n",'-'*45, sep='')
df

W         X         Y         Z
A  0.279915 -0.155202 -0.443393 -0.013906
B -1.399822 -1.022450 -0.482352  0.221707
C  0.620886 -1.129661  1.001841 -0.438784
D -1.644005 -0.573533 -1.404483 -0.685027
E -0.860188 -0.296077 -0.933756 -1.254459

In [45]:
df.iloc[2]

W    0.620886
X   -1.129661
Y    1.001841
Z   -0.438784
Name: C, dtype: float64

In [46]:
print("\nType of the pair of columns: ", type(df[['X','Z']]), sep='')
print ("\nSo, for more than one column, the object turns into a DataFrame")


Type of the pair of columns: <class 'pandas.core.frame.DataFrame'>

So, for more than one column, the object turns into a DataFrame


In [47]:
print("\nThe 'X' column accessed by DOT method (NOT recommended)\n",'-'*55, sep='')
print(df["X"])


The 'X' column accessed by DOT method (NOT recommended)
-------------------------------------------------------
A   -0.155202
B   -1.022450
C   -1.129661
D   -0.573533
E   -0.296077
Name: X, dtype: float64


In [48]:
print("\nA column is created by assigning it in relation to an existing column\n",'-'*75, sep='')
df['New'] = df['X']+df['Z']
df['New (Sum of X and Z)'] = df['X']+df['Z']
print(df)



A column is created by assigning it in relation to an existing column
---------------------------------------------------------------------------
          W         X         Y         Z       New  New (Sum of X and Z)
A  0.279915 -0.155202 -0.443393 -0.013906 -0.169108             -0.169108
B -1.399822 -1.022450 -0.482352  0.221707 -0.800743             -0.800743
C  0.620886 -1.129661  1.001841 -0.438784 -1.568445             -1.568445
D -1.644005 -0.573533 -1.404483 -0.685027 -1.258560             -1.258560
E -0.860188 -0.296077 -0.933756 -1.254459 -1.550536             -1.550536


In [49]:
df

W         X         Y         Z       New  New (Sum of X and Z)
A  0.279915 -0.155202 -0.443393 -0.013906 -0.169108             -0.169108
B -1.399822 -1.022450 -0.482352  0.221707 -0.800743             -0.800743
C  0.620886 -1.129661  1.001841 -0.438784 -1.568445             -1.568445
D -1.644005 -0.573533 -1.404483 -0.685027 -1.258560             -1.258560
E -0.860188 -0.296077 -0.933756 -1.254459 -1.550536             -1.550536

In [50]:
print("\nA column is dropped by using df.drop() method\n",'-'*55, sep=' ')
df.drop("C",inplace=True) # Notice the axis=1 option, axis = 0 is default, so one has to change it to 1




A column is dropped by using df.drop() method
 -------------------------------------------------------


In [51]:
df

W         X         Y         Z       New  New (Sum of X and Z)
A  0.279915 -0.155202 -0.443393 -0.013906 -0.169108             -0.169108
B -1.399822 -1.022450 -0.482352  0.221707 -0.800743             -0.800743
D -1.644005 -0.573533 -1.404483 -0.685027 -1.258560             -1.258560
E -0.860188 -0.296077 -0.933756 -1.254459 -1.550536             -1.550536

In [52]:
df1=df.drop('A')
print("\nA row (index) is dropped by using df.drop() method and axis=0\n",'-'*65, sep='')
print(df1)



A row (index) is dropped by using df.drop() method and axis=0
-----------------------------------------------------------------
          W         X         Y         Z       New  New (Sum of X and Z)
B -1.399822 -1.022450 -0.482352  0.221707 -0.800743             -0.800743
D -1.644005 -0.573533 -1.404483 -0.685027 -1.258560             -1.258560
E -0.860188 -0.296077 -0.933756 -1.254459 -1.550536             -1.550536


In [53]:
print("\nAn in-place change can be done by making inplace=True in the drop method\n",'-'*75, sep='')
df.drop('New (Sum of X and Z)', axis=1, inplace=True)
print(df)


An in-place change can be done by making inplace=True in the drop method
---------------------------------------------------------------------------
          W         X         Y         Z       New
A  0.279915 -0.155202 -0.443393 -0.013906 -0.169108
B -1.399822 -1.022450 -0.482352  0.221707 -0.800743
D -1.644005 -0.573533 -1.404483 -0.685027 -1.258560
E -0.860188 -0.296077 -0.933756 -1.254459 -1.550536


In [54]:
### Selecting/indexing Rows
#* Label-based 'loc' method
#* Index (numeric) 'iloc' method
df

W         X         Y         Z       New
A  0.279915 -0.155202 -0.443393 -0.013906 -0.169108
B -1.399822 -1.022450 -0.482352  0.221707 -0.800743
D -1.644005 -0.573533 -1.404483 -0.685027 -1.258560
E -0.860188 -0.296077 -0.933756 -1.254459 -1.550536

In [55]:
print("\nLabel-based 'loc' method can be used for selecting row(s)\n",'-'*60, sep='')
print("\nSingle row\n")
print(df.iloc[3])



Label-based 'loc' method can be used for selecting row(s)
------------------------------------------------------------

Single row

W     -0.860188
X     -0.296077
Y     -0.933756
Z     -1.254459
New   -1.550536
Name: E, dtype: float64


In [59]:
print("\nIndex position based 'iloc' method can be used for selecting row(s)\n",'-'*70, sep='')
print("\nSingle row\n")
print(df.iloc[2])



Index position based 'iloc' method can be used for selecting row(s)
----------------------------------------------------------------------

Single row

W     -1.644005
X     -0.573533
Y     -1.404483
Z     -0.685027
New   -1.258560
Name: D, dtype: float64


In [60]:
print("\nMultiple rows\n")
print(df.iloc[[1,2]])


Multiple rows

          W         X         Y         Z       New
B -1.399822 -1.022450 -0.482352  0.221707 -0.800743
D -1.644005 -0.573533 -1.404483 -0.685027 -1.258560


In [61]:
#### Subsetting DataFrame

In [62]:

matrix_data = rn(5,4)
row_labels = ['A','B','C','D','E']
column_headings = ['W','X','Y','Z']
df = pd.DataFrame(data=matrix_data, index=row_labels, columns=column_headings)



In [63]:
print("\nThe DatFrame\n",'-'*45, sep='')
print(df)



The DatFrame
---------------------------------------------
          W         X         Y         Z
A -0.447025  1.319771  1.088658 -0.919285
B -0.009131  1.425180  1.469456 -1.701735
C -0.270723 -0.714989 -1.093796  1.161190
D -0.960513 -0.156890  1.220352 -0.183394
E  0.830753 -0.920157 -0.047722  1.178664


In [64]:
print("\nElement at row 'B' and column 'Y' is\n") 
print(df.loc[['B','C'],['Y','W']])



Element at row 'B' and column 'Y' is

          Y         W
B  1.469456 -0.009131
C -1.093796 -0.270723


In [65]:
print("\nSubset comprising of rows B and D, and columns W and Y, is\n")
df.iloc[[1,2,3],[0,1]]


Subset comprising of rows B and D, and columns W and Y, is



W         X
B -0.009131  1.425180
C -0.270723 -0.714989
D -0.960513 -0.156890

In [66]:
print(df.loc[['B','C'],])

          W         X         Y         Z
B -0.009131  1.425180  1.469456 -1.701735
C -0.270723 -0.714989 -1.093796  1.161190


In [67]:
print("\nThe DataFrame\n",'-'*45, sep='')
print(df)



The DataFrame
---------------------------------------------
          W         X         Y         Z
A -0.447025  1.319771  1.088658 -0.919285
B -0.009131  1.425180  1.469456 -1.701735
C -0.270723 -0.714989 -1.093796  1.161190
D -0.960513 -0.156890  1.220352 -0.183394
E  0.830753 -0.920157 -0.047722  1.178664


In [68]:
print("\nBoolean DataFrame(s) where we are checking if the values are greater than 0\n",'-'*75, sep='')
print(df>0)



Boolean DataFrame(s) where we are checking if the values are greater than 0
---------------------------------------------------------------------------
       W      X      Y      Z
A  False   True   True  False
B  False   True   True  False
C  False  False  False   True
D  False  False   True  False
E   True  False  False   True


In [69]:
print("\n")
print(df.loc[['A','B','C']]>0)




       W      X      Y      Z
A  False   True   True  False
B  False   True   True  False
C  False  False  False   True


In [70]:
booldf = df>0
print("\nDataFrame indexed by boolean dataframe\n",'-'*45, sep='')
print(df[booldf])


DataFrame indexed by boolean dataframe
---------------------------------------------
          W         X         Y         Z
A       NaN  1.319771  1.088658       NaN
B       NaN  1.425180  1.469456       NaN
C       NaN       NaN       NaN  1.161190
D       NaN       NaN  1.220352       NaN
E  0.830753       NaN       NaN  1.178664


In [71]:

import pandas as pd 
import numpy as np
matrix_data = np.matrix('22,66,140;42,70,148;30,62,125;35,68,160;25,62,152')
row_labels = ['A','B','C','D','E']
column_headings = ['Age', 'Height', 'Weight']
matrix_data

matrix([[ 22,  66, 140],
        [ 42,  70, 148],
        [ 30,  62, 125],
        [ 35,  68, 160],
        [ 25,  62, 152]])

In [72]:
df = pd.DataFrame(data=matrix_data, index=row_labels, columns=column_headings)
print("\nA new DataFrame\n",'-'*25, sep='')
print(df)



A new DataFrame
-------------------------
   Age  Height  Weight
A   22      66     140
B   42      70     148
C   30      62     125
D   35      68     160
E   25      62     152


In [73]:
df[df['Height']>65]

Age  Height  Weight
A   22      66     140
B   42      70     148
D   35      68     160

In [74]:
print("\nRows with Height > 65 inch\n",'-'*35, sep='')
print(df[df['Height']>65])



Rows with Height > 65 inch
-----------------------------------
   Age  Height  Weight
A   22      66     140
B   42      70     148
D   35      68     160


In [75]:
df['Height']>65

A     True
B     True
C    False
D     True
E    False
Name: Height, dtype: bool

In [76]:
booldf1 = df['Height']>65
booldf2 = df['Weight']>145


In [77]:
print("\nRows with Height > 65 inch and Weight >145 lbs\n",'-'*55, sep='')
print(df[(booldf1) & (booldf2)])



Rows with Height > 65 inch and Weight >145 lbs
-------------------------------------------------------
   Age  Height  Weight
B   42      70     148
D   35      68     160


In [78]:
print("\nDataFrame with only Age and Weight columns whose Height > 65 inch\n",'-'*68, sep='')
print(df[booldf1][['Age','Weight']])


DataFrame with only Age and Weight columns whose Height > 65 inch
--------------------------------------------------------------------
   Age  Weight
A   22     140
B   42     148
D   35     160


In [79]:
matrix_data = np.matrix('22,66,140;42,70,148;30,62,125;35,68,160;25,62,152')
row_labels = ['A','B','C','D','E']
column_headings = ['Age', 'Height', 'Weight']


In [80]:
df = pd.DataFrame(data=matrix_data, index=row_labels, columns=column_headings)
print("\nThe DataFrame\n",'-'*25, sep='')
print(df)



The DataFrame
-------------------------
   Age  Height  Weight
A   22      66     140
B   42      70     148
C   30      62     125
D   35      68     160
E   25      62     152


In [81]:
print("\nAfter resetting index\n",'-'*35, sep='')
print(df.reset_index())



After resetting index
-----------------------------------
  index  Age  Height  Weight
0     A   22      66     140
1     B   42      70     148
2     C   30      62     125
3     D   35      68     160
4     E   25      62     152


In [82]:
print("\nAfter resetting index with 'drop' option TRUE\n",'-'*45, sep='')
print(df.reset_index(drop=True))
"Student Teacher Engineer Doctor Nurse".split()


After resetting index with 'drop' option TRUE
---------------------------------------------
   Age  Height  Weight
0   22      66     140
1   42      70     148
2   30      62     125
3   35      68     160
4   25      62     152


['Student', 'Teacher', 'Engineer', 'Doctor', 'Nurse']

In [83]:
print("\nAdding a new column 'Profession'\n",'-'*45, sep='')
df['Profession'] = "Student Teacher Engineer Doctor Nurse".split()
print(df)



Adding a new column 'Profession'
---------------------------------------------
   Age  Height  Weight Profession
A   22      66     140    Student
B   42      70     148    Teacher
C   30      62     125   Engineer
D   35      68     160     Doctor
E   25      62     152      Nurse


In [84]:
print("\nSetting 'Profession' column as index\n",'-'*45, sep='')
print (df.set_index('Profession'))


Setting 'Profession' column as index
---------------------------------------------
            Age  Height  Weight
Profession                     
Student      22      66     140
Teacher      42      70     148
Engineer     30      62     125
Doctor       35      68     160
Nurse        25      62     152


In [85]:
#multi-indexing
# Index Levels
outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside))


In [86]:
print("\nTuple pairs after the zip and list command\n",'-'*45, sep='')
print(hier_index)



Tuple pairs after the zip and list command
---------------------------------------------
[('G1', 1), ('G1', 2), ('G1', 3), ('G2', 1), ('G2', 2), ('G2', 3)]


In [87]:
hier_index = pd.MultiIndex.from_tuples(hier_index)
print("\nIndex hierarchy\n",'-'*25, sep='')
print(hier_index)




Index hierarchy
-------------------------
MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )


In [88]:
print("\nIndex hierarchy type\n",'-'*25, sep='')
print(type(hier_index))



Index hierarchy type
-------------------------
<class 'pandas.core.indexes.multi.MultiIndex'>


In [89]:
print("\nCreating DataFrame with multi-index\n",'-'*37, sep='')
#np.random.seed(101)
df1 = pd.DataFrame(data=np.round(rn(6,3)), index= hier_index, columns= ['A','B','C'])
print(df1)



Creating DataFrame with multi-index
-------------------------------------
        A    B    C
G1 1  1.0 -0.0 -0.0
   2  0.0 -1.0 -1.0
   3  1.0 -0.0 -1.0
G2 1 -1.0  0.0  2.0
   2  1.0  1.0  1.0
   3 -2.0  1.0  0.0


In [90]:
#cross tabulation like pivot table

In [91]:
print("\nGrabbing a cross-section from outer level\n",'-'*45, sep='')
print(df1.xs('G1'))



Grabbing a cross-section from outer level
---------------------------------------------
     A    B    C
1  1.0 -0.0 -0.0
2  0.0 -1.0 -1.0
3  1.0 -0.0 -1.0
